# Generated by Django 5.0.14 on 2025-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('capacity', 'Capacity Management'), ('problem', 'Problem Analysis'), ('user', 'User Management'), ('software', 'Software Inventory')], max_length=50)),
                ('tenant_url', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('management_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('timeframe', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('report_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('pptx', 'PPTX')], max_length=10)),
                ('recurrence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('next_run', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProblemReportSchedule',
        ),
    ]
