# Generated by Django 5.0.14 on 2025-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scheduledreport_delete_problemreportschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='account_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='recurrence',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='report_format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='tenant_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
