# Generated by Django 5.0.14 on 2025-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_scheduledreport_account_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='recipient_email',
            field=models.TextField(),
        ),
    ]
