# Generated by Django 5.0.7 on 2026-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_scheduledreport_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('host_availability', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('record_date', models.DateField()),
            ],
        ),
    ]
