# Generated by Django 5.0.7 on 2026-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_infra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('request_count', models.FloatField()),
                ('response_time', models.FloatField()),
                ('failure_rate', models.FloatField()),
                ('record_date', models.DateField()),
            ],
        ),
    ]
