# Generated by Django 5.0.7 on 2026-01-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_servicemetrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceMetrics',
            new_name='Service',
        ),
    ]
