# Generated by Django 5.0.7 on 2026-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_servicemetrics_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('availability', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('record_date', models.DateField()),
            ],
        ),
    ]
