# Generated by Django 5.0.7 on 2026-01-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infra',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
