# Generated by Django 5.0.7 on 2026-01-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_host_process_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('service_name', 'record_date')},
        ),
    ]
