# Generated by Django 5.0.7 on 2026-01-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_service_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('host_name', 'record_date')},
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('process_name', 'record_date')},
        ),
    ]
