# Generated by Django 5.0.7 on 2026-01-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_host_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
