# Generated by Django 5.0.7 on 2026-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_delete_host_delete_process_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('host_availability', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('record_date', models.DateField()),
            ],
            options={
                'unique_together': {('host_name', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('availability', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('record_date', models.DateField()),
            ],
            options={
                'unique_together': {('process_name', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('request_count', models.FloatField()),
                ('response_time', models.FloatField()),
                ('failure_rate', models.FloatField()),
                ('record_date', models.DateField()),
            ],
            options={
                'unique_together': {('service_name', 'record_date')},
            },
        ),
    ]
