"""
Django settings for dynatrace_tracker project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, sys
from django.contrib.auth.decorators import login_required
import sys
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rx00$$v-l3m*%nvv7$oi=!=%@&454a#(22925r!^h8zxn*pk#-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

import os
import logging

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%d-%b-%Y %I:%M:%S %p",
        },
    },

    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "app.log"),
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },

    "loggers": {
        # APScheduler logs
        "apscheduler": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        # Django internals (requests, etc)
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "django.request": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": False,
        },

        # your app package logger (dashboard)
        "dashboard": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        # root (fallback)
        "": {
            "handlers": ["file", "console"],
            "level": "INFO",
        },
    },
}

# Application definition

INSTALLED_APPS = [
    'dashboard.apps.DashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',       # ✅ add this line
    'apscheduler', 
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dynatrace_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': ['templates'],
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dynatrace_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Use EXE directory instead of PyInstaller temp folder
# DB_PATH = os.path.join(os.path.dirname(sys.argv[0]), "db.sqlite3")

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': DB_PATH,
#     }
# }
# ------------------------------------------------------
#  PERSISTENT DATABASE OUTSIDE THE EXE
# ------------------------------------------------------

# Permanent storage location (AppData\Local\KarvOps)
USER_DATA_DIR = os.path.join(
    os.environ.get("LOCALAPPDATA") or os.path.expanduser("~"),
    "KarvOps"
)
os.makedirs(USER_DATA_DIR, exist_ok=True)

PERSISTENT_DB = os.path.join(USER_DATA_DIR, "db.sqlite3")

# Detect if running from PyInstaller EXE
RUNNING_IN_EXE = hasattr(sys, "_MEIPASS") or os.environ.get("PYINSTALLER_RUNNING") == "true"

if RUNNING_IN_EXE:
    # On first run → copy DB out of the EXE bundle
    if not os.path.exists(PERSISTENT_DB):
        try:
            bundled_db = os.path.join(sys._MEIPASS, "db.sqlite3")
            if os.path.exists(bundled_db):
                import shutil
                shutil.copy2(bundled_db, PERSISTENT_DB)
        except Exception as e:
            print("DB COPY ERROR:", e)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": PERSISTENT_DB,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Added Maunally 

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"



LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'


# settings.py
# Email configuration (example using Gmail SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "karvtech3@gmail.com"
EMAIL_HOST_PASSWORD = "kyid knyd hzcz hugy"   # or App Password if using Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# APScheduler settings
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # date format
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds


# Auto logout after 1 hour of inactivity
# SESSION_COOKIE_AGE = 3600          # 3600 seconds = 1 hour
# SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# SESSION_COOKIE_SAMESITE = "Lax"
